version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  nodejs:
    build:
      context: .
      args:
        NODE_ENV: production
    restart: always
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    command: node src/index.js

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    image: redis
    volumes:
      - redis-cache:/data
    restart: always

volumes:
  mongo-db:
  redis-cache:
