version: '3'
services:
  nginx:
    ports:
      - '3000:80'

  nodejs:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run start_dev

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
